KeyUp : z
KeyDown : s
KeyLeft : q
KeyRight : d
KeyUpLeft : a
KeyUpRight : e
KeyUpLeft : w
KeyUpRight : c
KeyQuit : 27
NbColumn : 10
NbRow : 10
ColorP1 : KBlue
ColorP2 :  KGreen
TokenP1 : X
TokenP2 : O
