KeyUp : 90
KeyDown : 83
KeyLeft : 81
KeyRight : 68
KeyUpLeft : 65
KeyUpRight : 69
KeyDownLeft : 87
KeyDownRight : 67
KeyQuit : 27
NbColumn : 15
NbRow : 15
ColorP1 : KBlue
ColorP2 :  KGreen
TokenP1 : X
TokenP2 : O
